// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Com01: typeof import('./src/components/demos/Com01.vue')['default']
    TreeView: typeof import('./src/components/home/TreeView.vue')['default']
  }
}

export { }
